apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  discovery.type: {{ .Values.elasticsearch.discovery_type }}
  xpack.security.enabled: "{{ .Values.elasticsearch.security_enabled }}"
  ES_JAVA_OPTS: "{{ .Values.elasticsearch.java_opts }}"
