apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config-master
  namespace: {{ .Release.Namespace }}
data:
  pg_hba.conf: |
{{ .Values.postgresql.master.config.pg_hba_conf | indent 4 }}
  
  postgresql.conf: |
{{ .Values.postgresql.master.config.postgresql_conf | indent 4 }}

  init_script.sh: |
{{ .Values.postgresql.master.config.init_script | indent 4 }}
