---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgresql.master.name }}
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ .Values.postgresql.master.service.name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgresql.master.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgresql.master.name }}
    spec:
      containers:
      - name: postgres
        image: {{ .Values.postgresql.master.image }}
        command:
          - bash
          - -c
          - |
            docker-entrypoint.sh \
              -c config_file=/etc/postgresql/postgresql.conf \
              -c hba_file=/etc/postgresql/pg_hba.conf
        ports:
          - containerPort: {{ .Values.postgresql.master.service.port }}
        env:
          - name: PGDATA
            value: /data/postgres
          - name: POSTGRES_DB
            value: {{ .Values.postgresql.master.env.POSTGRES_DB }}
          - name: POSTGRES_USER
            value: {{ .Values.postgresql.master.env.POSTGRES_USER }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.postgresql.master.env.POSTGRES_PASSWORD }}
        resources:
          requests:
            memory: {{ .Values.postgresql.master.resources.requests.memory }}
            cpu: {{ .Values.postgresql.master.resources.requests.cpu }}
        volumeMounts:
          - name: data
            mountPath: /data/postgres
          - name: config
            mountPath: /etc/postgresql
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-config-master
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.postgresql.storage.size }}
