apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.scrape_interval }}
    scrape_configs:
      - job_name: 'cadvisor'
        static_configs:
          - targets: ['{{ .Values.cadvisor.target }}']
