apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  prometheus.yml: |
{{ .Values.prometheus.config.promethus_yml | indent 4 }}

  rules.yml: |
{{ .Values.prometheus.config.rules_yml | indent 4 }}
