apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-website
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-website
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-website
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: website
        ports:
          - containerPort: {{ .Values.service.targetPort }}
