image:
  repository: otel/opentelemetry-collector
  tag: 0.95.0

replicaCount: 1

service:
  ports:
    grpc:
      port: 4317
      targetPort: 4317
      protocol: TCP
    http:
      port: 4318
      targetPort: 4318
      protocol: TCP

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  processors:
    batch: {}

  exporters:
    logging:
      loglevel: debug
    otlp:
      endpoint: tempo:4317
      tls:
        insecure: true

  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [logging, otlp]
