postgresql:
  storage:
    size: 1Gi

  master:
    name: postgres-master
    image: postgres:14
    service:
      name: postgres-master-headless
      port: 5432
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
    env:
      POSTGRES_DB: crawler
      POSTGRES_USER: crawler
      POSTGRES_PASSWORD: asdasd123
      POSTGRES_REPLICATION_USER: crawler
      POSTGRES_REPLICATION_PASSWORD: asdasd123

  replica:
    name: postgres-replica
    image: postgres:14
    service:
      name: postgres-replica-headless
      port: 5432
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
    env:
      POSTGRES_MASTER_USER: crawler
      POSTGRES_MASTER_PASSWORD: asdasd123
      POSTGRES_REPLICATION_USER: crawler
      POSTGRES_REPLICATION_PASSWORD: asdasd123
      POSTGRES_MASTER_SERVICE: postgres-master-headless

config:
  pg_hba_conf: |
    local   all             all                                     trust
    host    all             all             127.0.0.1/32            trust
    host    all             all             ::1/128                 trust
    local   replication     all                                     trust
    host    replication     all             127.0.0.1/32            trust
    host    replication     all             ::1/128                 trust
    host all all all scram-sha-256
  
  postgresql_conf: |
    listen_addresses = '*'
    port = 5432
    shared_buffers = 128MB
    work_mem = 4MB
    maintenance_work_mem = 64MB
    logging_collector = on
    log_directory = 'pg_log'
    log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
    log_statement = 'all'
    log_min_duration_statement = 1000
    max_connections = 100
    effective_cache_size = 256MB
    checkpoint_timeout = 5min
    wal_level = logical
    max_replication_slots = 4
    max_wal_senders = 4
    max_wal_size = 1GB
    min_wal_size = 80MB
    checkpoint_completion_target = 0.7
    autovacuum = on
    autovacuum_naptime = 10s
