image:
  repository: grafana/tempo
  tag: main-3738ab8

replicaCount: 1

service:
  ports:
    grpc:
      port: 4317
      targetPort: 4317
    http:
      port: 3200
      targetPort: 3200

config:
  auth_enabled: false
  server:
    http_listen_port: 3200
    log_level: info
  distributor:
    receivers:
      otlp:
        protocols:
          grpc: {}
  storage:
    trace:
      backend: local
      wal:
        path: /tmp/tempo/wal
      local:
        path: /tmp/tempo/blocks
  compactor:
    compaction:
      compacted_block_retention: 0s
