# ingress-nginx
- name: Add stable chart repo ingress-nginx
  kubernetes.core.helm_repository:
    kubeconfig: "{{ kubeconfig }}"
    name: stable
    repo_url: "https://kubernetes.github.io/ingress-nginx"

- name: Install ingress-nginx
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig }}"
    release_state: "{{ k8s_state }}"
    chart_ref: stable/ingress-nginx
    release_name: ingress-nginx
    release_namespace: ingress-nginx
