apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  ELASTICSEARCH_HOSTS: "{{ .Values.kibana.elasticsearch_host }}"
  KIBANA_PATH: "{{ .Values.kibana.kibana_path }}"
