# templates/ingress.yaml

{{- if .Values.kibana.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $key, $value := .Values.kibana.ingress.annotations }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
spec:
  ingressClassName: nginx
  # tls:
  # - hosts:
  #   - {{ .Values.kibana.ingress.host }}
  #   secretName: tls-{{ .Values.kibana.ingress.host }}
  rules:
    - host: {{ .Values.kibana.ingress.host }}
      http:
        paths:
          - path: {{ .Values.kibana.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 5601
{{- end }}
