apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: {{ .Values.config.receivers.otlp.protocols.grpc.endpoint }}
          http:
            endpoint: {{ .Values.config.receivers.otlp.protocols.http.endpoint }}
    
    processors:
      batch: {{ .Values.config.processors.batch }}

    exporters:
      logging:
        loglevel: {{ .Values.config.exporters.logging.loglevel }}
      otlp:
        endpoint: {{ .Values.config.exporters.otlp.endpoint }}
        tls:
          insecure: {{ .Values.config.exporters.otlp.tls.insecure }}

    service:
      pipelines:
        traces:
          receivers: {{ .Values.config.service.pipelines.traces.receivers }}
          processors: {{ .Values.config.service.pipelines.traces.processors }}
          exporters: {{ .Values.config.service.pipelines.traces.exporters }}
