- name: Install API application
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig }}"
    release_state: "{{ k8s_state }}"
    chart_ref: "../../helm/application/app/api" # resource
    release_name: api
    release_namespace: application

- name: Install Website application
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig }}"
    release_state: "{{ k8s_state }}"
    chart_ref: "../../helm/application/app/website" # resource
    release_name: website
    release_namespace: application
