apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
      # Log_Level
      # =========
      # - error
      # - warning
      # - info
      # - debug
      # - trace
      # Default 'info' is set, that means it includes 'error' and 'warning'.
      Flush 5
      log_level info

    [INPUT]
      Name tail
      Tag kube.*
      Path /var/log/containers/*.log
      multiline.parser docker, cri
      Mem_Buf_Limit 5MB
      Skip_Long_Lines On

    [INPUT]
      Name tail
      Tag nginx.*
      Path /var/log/containers/ingress-nginx-*.log
      multiline.parser docker, cri
      Mem_Buf_Limit 5MB
      Skip_Long_Lines On

    [FILTER]
      Name kubernetes
      Match kube.*
      Merge_Log On
      Keep_Log Off
      K8S-Logging.Parser On
      K8S-Logging.Exclude On

    [FILTER]
      Name grep
      Match kube.*
      Exclude $kubernetes['namespace_name'] logging

    [OUTPUT]
      Name stdout
      Match kube.*

    # https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch
    [OUTPUT]
      Name es
      Match nginx.*
      Host  elasticsearch-0.elasticsearch-headless.logging.svc.cluster.local
      Port  9200
      Index nginx-log
      Suppress_Type_Name On
      Retry_Limit False

    [OUTPUT]
      Name loki
      Match *
      Host loki-0.loki-headless.monitoring.svc.cluster.local
      Port 3100
      Line_Format json
