{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Namespace }}-{{ .Values.rbac.roleBinding.name }}
  namespace: {{ .Release.Namespace }}
rules:
{{- toYaml .Values.rbac.rules | nindent 2 }}
{{- end }}