apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "crawler-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ include "crawler-chart.fullname" . }}-cronjob
        spec:
          restartPolicy: OnFailure
          containers:
          - name: {{ include "crawler-chart.fullname" . }}
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            env:
              - name: REDIS_HOST
                value: {{ .Values.redis.host }}
              - name: REDIS_PORT
                value: {{ .Values.redis.port | quote }}
              - name: REDIS_PASS
                value: {{ .Values.redis.password }}
