apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../templates

namespace: prod

nameSuffix: -prod

patches:
  - target:
      kind: Deployment
      name: redis-prod
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
