postgresql:
  storage:
    size: 1Gi

  replica:
    name: postgres-replica
    image: postgres:14
    service:
      name: postgres-replica-headless
      port: 5432
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
    env:
      POSTGRES_USER_REPLICA: repuser
      POSTGRES_PASSWORD_REPLICA: asdasd123
