apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: onlylight291998/crawler-api
        name: api
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 200m
        env:
          - name: POSTGRES_DNS
            value: postgres://crawler:asdasd123@postgres-0.postgres-headless:5432/crawler?sslmode=disable
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: api
