apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  # serviceAccountName: dev-developer-sa
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "api-chart.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "api-chart.fullname" . }}
        env: {{ .Values.environment.active }}
    spec:
      containers:
        - name: api
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: POSTGRES_DNS
              value: {{ .Values.env.POSTGRES_DNS | quote }}
            - name: OTLP_EXPORTER
              value: {{ .Values.env.OTLP_EXPORTER | quote }}
