apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ include "api-chart.fullname" . }}
    env: {{ .Values.environment.active }}
