apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    auth_enabled: {{ .Values.config.auth_enabled }}
    server:
      http_listen_port: {{ .Values.config.server.http_listen_port }}
      log_level: {{ .Values.config.server.log_level }}

    distributor:
      receivers:
        otlp:
          protocols:
            grpc: {}

    storage:
      trace:
        backend: {{ .Values.config.storage.trace.backend }}
        wal:
          path: {{ .Values.config.storage.trace.wal.path }}
        local:
          path: {{ .Values.config.storage.trace.local.path }}

    compactor:
      compaction:
        compacted_block_retention: {{ .Values.config.compactor.compaction.compacted_block_retention }}
