replicaCount: 1

image:
  repository: grafana/grafana
  tag: latest

service:
  port: 3000
  targetPort: 3000

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # cert-manager.io/issuer: "letsencrypt-prod"
  # host: grafana.local
  host: grafana.onlylight.click
  path: /
  pathType: Prefix

admin:
  user: admin
  password: admin
