- name: Setup and Customize Amazon EKS
  hosts: eks_dev
  gather_facts: false

  tasks:
  - name: Create namespacess
    include_tasks: ../tasks/namespaces.yaml

  # - name: Install Storage Class
  #   kubernetes.core.k8s:
  #     kubeconfig: "{{ kubeconfig }}"
  #     state: present
  #     src: "../../helm/storageclass.yaml" # resource

  # - name: setup database & redis cache
  #   include_tasks: ../tasks/store.yaml

  # - name: setup scrape data application
  #   include_tasks: ../tasks/scrape_data.yaml

  # - name: Add stable chart repo ingress-nginx
  #   kubernetes.core.helm_repository:
  #     name: stable
  #     release_namespace: ingress-nginx
  #     repo_url: "https://kubernetes.github.io/ingress-nginx"
