- name: Setup and Customize Amazon EKS
  hosts: eks_dev
  gather_facts: false

  vars:
    env: dev

  tasks:
  - name: Create namespaces
    include_tasks:
      file: "../tasks/namespaces.yaml"
      apply:
        vars:
          k8s_state: "{{ state | default('present') }}"

  - name: Install Storage Class
    kubernetes.core.k8s:
      kubeconfig: "{{ kubeconfig }}"
      state: "{{ state | default('present') }}"
      src: "../../helm/storageclass.yaml"
      namespace: "{{ env }}"

  # - name: Install resources through helm chart repo
  #   include_tasks:
  #     file: "../tasks/repository_resources/argocd.yaml"
  #     apply:
  #       vars:
  #         k8s_state: "{{ state | default('present') }}"

  - name: Setup Postgres and redis cache
    include_tasks:
      file: "../tasks/data/main.yaml"
      apply:
        vars:
          k8s_state: "{{ state | default('present') }}"
          env: "{{ env }}"

  - name: Ready for scrape data
    include_tasks:
      file: "../tasks/app/scrape_data.yaml"
      apply:
        vars:
          k8s_state: "{{ state | default('present') }}"
          env: "{{ env }}"

  - name: Setup Application
    include_tasks:
      file: "../tasks/app/application.yaml"
      apply:
        vars:
          k8s_state: "{{ state | default('present') }}"
          env: "{{ env }}"

  - name: Setup Logging system
    include_tasks:
      file: "../tasks/logging/main.yaml"
      apply:
        vars:
          k8s_state: "{{ state | default('present') }}"

  - name: Setup Metric system
    include_tasks:
      file: "../tasks/metrics/main.yaml"
      apply:
        vars:
          k8s_state: "{{ state | default('present') }}"

  - name: Setup Tracing system
    include_tasks:
      file: "../tasks/tracing/main.yaml"
      apply:
        vars:
          k8s_state: "{{ state | default('present') }}"

  # - name: Setup ArgoCD application manage system
  #   include_tasks:
  #     file: "../tasks/argocd/main.yaml"
  #     apply:
  #       vars:
  #         k8s_state: "{{ state | default('present') }}"
