- name: Create k8s namespace application
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: application
    api_version: v1
    kind: Namespace
    state: "{{ k8s_state }}"

- name: Create k8s namespace tracing
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: tracing
    api_version: v1
    kind: Namespace
    state: "{{ k8s_state }}"

- name: Create k8s namespace monitoring
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: monitoring
    api_version: v1
    kind: Namespace
    state: "{{ k8s_state }}"

- name: Create k8s namespace logging
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: logging
    api_version: v1
    kind: Namespace
    state: "{{ k8s_state }}"

- name: Create k8s namespace argocd
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: argocd
    api_version: v1
    kind: Namespace
    state: "{{ k8s_state }}"
