- name: Create k8s namespace ingress-nginx
  kubernetes.core.k8s:
    name: ingress-nginx
    api_version: v1
    kind: Namespace
    state: "{{ k8s_state }}"

- name: Create k8s namespace tracing
  kubernetes.core.k8s:
    name: tracing
    api_version: v1
    kind: Namespace
    state: "{{ k8s_state }}"

- name: Create k8s namespace monitoring
  kubernetes.core.k8s:
    name: monitoring
    api_version: v1
    kind: Namespace
    state: "{{ k8s_state }}"

- name: Create k8s namespace logging
  kubernetes.core.k8s:
    name: logging
    api_version: v1
    kind: Namespace
    state: "{{ k8s_state }}"

- name: Create k8s namespace argocd
  kubernetes.core.k8s:
    name: argocd
    api_version: v1
    kind: Namespace
    state: "{{ k8s_state }}"
