# - name: Install Crawler
#   kubernetes.core.k8s:
#     kubeconfig: "{{ kubeconfig }}"
#     state: present
#     src: "../../helm/application/scrape_data/crawler" # resource

# - name: Install Migrate Initial
#   kubernetes.core.k8s:
#     kubeconfig: "{{ kubeconfig }}"
#     state: present
#     src: "../../helm/application/scrape_data/migrate-init" # resource

# - name: Install Migrate
#   kubernetes.core.k8s:
#     kubeconfig: "{{ kubeconfig }}"
#     state: present
#     src: "../../helm/application/scrape_data/migrate" # resource

# - name: Install Consumer
#   kubernetes.core.k8s:
#     kubeconfig: "{{ kubeconfig }}"
#     state: present
#     src: "../../helm/application/scrape_data/consumer" # resource