- name: Install Postgres Master
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig }}"
    chart_path: "../../helm/application/postgres-master" # resource
    release_name: postgres-master

# - name: Install Postgres Replica
#   kubernetes.core.helm:
#     kubeconfig: "{{ kubeconfig }}"
#     state: present
#     chart_path: "../../helm/application/postgres-replica" # resource
#     release_name: postgres-replica

# - name: Install Redis
#   kubernetes.core.helm:
#     kubeconfig: "{{ kubeconfig }}"
#     state: present
#     chart_path: "../../helm/application/redis" # resource
#     release_name: redis