apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "consumer-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "consumer-chart.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "consumer-chart.fullname" . }}
    spec:
      containers:
        - name: consumer
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: REDIS_HOST
              value: {{ .Values.redis.host }}
            - name: REDIS_PORT
              value: {{ .Values.redis.port | quote }}
            - name: REDIS_PASS
              value: {{ .Values.redis.password }}
            - name: POSTGRES_DNS
              value: {{ .Values.postgres.dns }}
