apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: tracing
  labels:
    app: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
      - name: tempo
        image: grafana/tempo:main-3738ab8
        args:
        - "-config.file=/etc/tempo.yaml"
        ports:
        - containerPort: 4317
        - containerPort: 3200
        volumeMounts:
        - name: config-volume
          mountPath: /etc/tempo.yaml
          subPath: config.yaml
        - name: data-volume
          mountPath: /tmp/tempo
      volumes:
      - name: config-volume
        configMap:
          name: tempo-config
      - name: data-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: tracing
spec:
  selector:
    app: tempo
  ports:
    - name: grpc
      port: 4317
      targetPort: 4317
    - name: http
      port: 3200
      targetPort: 3200
