apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: logging
data:
  ELASTICSEARCH_HOSTS: "http://elasticsearch-0.elasticsearch-headless.logging.svc.cluster.local:9200"
  KIBANA_PATH: "/kibana"
