name: alertmanager

replicas: 1

image:
  repository: prom/alertmanager
  tag: latest

ports:
  containerPort: 9090
  servicePort: 9090

resources:
  requests:
    cpu: 500m
    memory: 500M
  limits:
    cpu: 1
    memory: 1Gi
