apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config-replica
  namespace: {{ .Release.Namespace }}
data:
  pg_hba.conf: |
{{ .Values.postgresql.replica.config.pg_hba_conf | indent 4 }}
  
  postgresql.conf: |
{{ .Values.postgresql.replica.config.postgresql_conf | indent 4 }}
