---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgresql.replica.name }}
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ .Values.postgresql.replica.service.name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgresql.replica.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgresql.replica.name }}
    spec:

      containers:
      - name: postgres
        image: {{ .Values.postgresql.replica.image }}
        ports:
          - containerPort: {{ .Values.postgresql.replica.service.port }}
        env:
          - name: PGDATA
            value: /data/postgres
          - name: POSTGRES_USER
            value: {{ .Values.postgresql.replica.env.POSTGRES_USER_REPLICA }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.postgresql.replica.env.POSTGRES_PASSWORD_REPLICA }}
        resources:
          requests:
            memory: {{ .Values.postgresql.replica.resources.requests.memory }}
            cpu: {{ .Values.postgresql.replica.resources.requests.cpu }}
        volumeMounts:
          - mountPath: /data/postgres
            name: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-master-pvc
