apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../templates

namespace: dev

nameSuffix: -dev

patches:
  - target:
      kind: Deployment
      name: redis-dev
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
