# helm repo add argo https://argoproj.github.io/argo-helm
# helm repo update
# helm install argocd argo/argo-cd -n argocd --create-namespace
# kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d

server:
  # Expose ArgoCD server on HTTP (no SSL) for simplicity in local setup
  ingress:
    enabled: true
    ingressClassName: nginx  # assuming NGINX ingress controller
    hostname: "argocd-helm.local"
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"  # Disable SSL redirect for HTTP
      nginx.ingress.kubernetes.io/use-regex: "true"

  # Disable auto TLS setup for ArgoCD server
  extraArgs:
    - --insecure
