kibana:
  image: docker.elastic.co/kibana/kibana:8.12.0
  replicas: 1
  elasticsearch_host: "http://elasticsearch-0.elasticsearch-headless.logging.svc.cluster.local:9200"
  kibana_path: "/kibana"
  ingress:
    enabled: true
    # host: kibana.local
    host: kibana.onlylight.click
    path: /
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      # cert-manager.io/issuer: "letsencrypt-prod"
